yandex: &default
  service: S3
  endpoint: https://storage.yandexcloud.net
  access_key_id: <%= Rails.application.credentials.dig(:aws, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:aws, :secret_access_key) %>
  region: ru-central-1
  bucket: animelib-s3-stoke

test:
  <<: *default
  bucket: animelib-test

production:
  <<: *default
  bucket: animelib
